# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/didier/projets/c/lldbmi2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/didier/projets/c/lldbmi2/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/didier/projets/c/lldbmi2/build/CMakeFiles /home/didier/projets/c/lldbmi2/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/didier/projets/c/lldbmi2/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lldbmi2

# Build rule for target.
lldbmi2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lldbmi2
.PHONY : lldbmi2

# fast build rule for target.
lldbmi2/fast:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/build
.PHONY : lldbmi2/fast

src/engine.o: src/engine.cpp.o

.PHONY : src/engine.o

# target to build an object file
src/engine.cpp.o:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/engine.cpp.o
.PHONY : src/engine.cpp.o

src/engine.i: src/engine.cpp.i

.PHONY : src/engine.i

# target to preprocess a source file
src/engine.cpp.i:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/engine.cpp.i
.PHONY : src/engine.cpp.i

src/engine.s: src/engine.cpp.s

.PHONY : src/engine.s

# target to generate assembly for a file
src/engine.cpp.s:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/engine.cpp.s
.PHONY : src/engine.cpp.s

src/events.o: src/events.cpp.o

.PHONY : src/events.o

# target to build an object file
src/events.cpp.o:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/events.cpp.o
.PHONY : src/events.cpp.o

src/events.i: src/events.cpp.i

.PHONY : src/events.i

# target to preprocess a source file
src/events.cpp.i:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/events.cpp.i
.PHONY : src/events.cpp.i

src/events.s: src/events.cpp.s

.PHONY : src/events.s

# target to generate assembly for a file
src/events.cpp.s:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/events.cpp.s
.PHONY : src/events.cpp.s

src/frames.o: src/frames.cpp.o

.PHONY : src/frames.o

# target to build an object file
src/frames.cpp.o:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/frames.cpp.o
.PHONY : src/frames.cpp.o

src/frames.i: src/frames.cpp.i

.PHONY : src/frames.i

# target to preprocess a source file
src/frames.cpp.i:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/frames.cpp.i
.PHONY : src/frames.cpp.i

src/frames.s: src/frames.cpp.s

.PHONY : src/frames.s

# target to generate assembly for a file
src/frames.cpp.s:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/frames.cpp.s
.PHONY : src/frames.cpp.s

src/lldbmi2.o: src/lldbmi2.cpp.o

.PHONY : src/lldbmi2.o

# target to build an object file
src/lldbmi2.cpp.o:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/lldbmi2.cpp.o
.PHONY : src/lldbmi2.cpp.o

src/lldbmi2.i: src/lldbmi2.cpp.i

.PHONY : src/lldbmi2.i

# target to preprocess a source file
src/lldbmi2.cpp.i:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/lldbmi2.cpp.i
.PHONY : src/lldbmi2.cpp.i

src/lldbmi2.s: src/lldbmi2.cpp.s

.PHONY : src/lldbmi2.s

# target to generate assembly for a file
src/lldbmi2.cpp.s:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/lldbmi2.cpp.s
.PHONY : src/lldbmi2.cpp.s

src/log.o: src/log.cpp.o

.PHONY : src/log.o

# target to build an object file
src/log.cpp.o:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/log.cpp.o
.PHONY : src/log.cpp.o

src/log.i: src/log.cpp.i

.PHONY : src/log.i

# target to preprocess a source file
src/log.cpp.i:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/log.cpp.i
.PHONY : src/log.cpp.i

src/log.s: src/log.cpp.s

.PHONY : src/log.s

# target to generate assembly for a file
src/log.cpp.s:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/log.cpp.s
.PHONY : src/log.cpp.s

src/names.o: src/names.cpp.o

.PHONY : src/names.o

# target to build an object file
src/names.cpp.o:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/names.cpp.o
.PHONY : src/names.cpp.o

src/names.i: src/names.cpp.i

.PHONY : src/names.i

# target to preprocess a source file
src/names.cpp.i:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/names.cpp.i
.PHONY : src/names.cpp.i

src/names.s: src/names.cpp.s

.PHONY : src/names.s

# target to generate assembly for a file
src/names.cpp.s:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/names.cpp.s
.PHONY : src/names.cpp.s

src/stringb.o: src/stringb.cpp.o

.PHONY : src/stringb.o

# target to build an object file
src/stringb.cpp.o:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/stringb.cpp.o
.PHONY : src/stringb.cpp.o

src/stringb.i: src/stringb.cpp.i

.PHONY : src/stringb.i

# target to preprocess a source file
src/stringb.cpp.i:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/stringb.cpp.i
.PHONY : src/stringb.cpp.i

src/stringb.s: src/stringb.cpp.s

.PHONY : src/stringb.s

# target to generate assembly for a file
src/stringb.cpp.s:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/stringb.cpp.s
.PHONY : src/stringb.cpp.s

src/strlxxx.o: src/strlxxx.cpp.o

.PHONY : src/strlxxx.o

# target to build an object file
src/strlxxx.cpp.o:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/strlxxx.cpp.o
.PHONY : src/strlxxx.cpp.o

src/strlxxx.i: src/strlxxx.cpp.i

.PHONY : src/strlxxx.i

# target to preprocess a source file
src/strlxxx.cpp.i:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/strlxxx.cpp.i
.PHONY : src/strlxxx.cpp.i

src/strlxxx.s: src/strlxxx.cpp.s

.PHONY : src/strlxxx.s

# target to generate assembly for a file
src/strlxxx.cpp.s:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/strlxxx.cpp.s
.PHONY : src/strlxxx.cpp.s

src/test.o: src/test.cpp.o

.PHONY : src/test.o

# target to build an object file
src/test.cpp.o:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/test.cpp.o
.PHONY : src/test.cpp.o

src/test.i: src/test.cpp.i

.PHONY : src/test.i

# target to preprocess a source file
src/test.cpp.i:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/test.cpp.i
.PHONY : src/test.cpp.i

src/test.s: src/test.cpp.s

.PHONY : src/test.s

# target to generate assembly for a file
src/test.cpp.s:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/test.cpp.s
.PHONY : src/test.cpp.s

src/variables.o: src/variables.cpp.o

.PHONY : src/variables.o

# target to build an object file
src/variables.cpp.o:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/variables.cpp.o
.PHONY : src/variables.cpp.o

src/variables.i: src/variables.cpp.i

.PHONY : src/variables.i

# target to preprocess a source file
src/variables.cpp.i:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/variables.cpp.i
.PHONY : src/variables.cpp.i

src/variables.s: src/variables.cpp.s

.PHONY : src/variables.s

# target to generate assembly for a file
src/variables.cpp.s:
	$(MAKE) -f CMakeFiles/lldbmi2.dir/build.make CMakeFiles/lldbmi2.dir/src/variables.cpp.s
.PHONY : src/variables.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... lldbmi2"
	@echo "... src/engine.o"
	@echo "... src/engine.i"
	@echo "... src/engine.s"
	@echo "... src/events.o"
	@echo "... src/events.i"
	@echo "... src/events.s"
	@echo "... src/frames.o"
	@echo "... src/frames.i"
	@echo "... src/frames.s"
	@echo "... src/lldbmi2.o"
	@echo "... src/lldbmi2.i"
	@echo "... src/lldbmi2.s"
	@echo "... src/log.o"
	@echo "... src/log.i"
	@echo "... src/log.s"
	@echo "... src/names.o"
	@echo "... src/names.i"
	@echo "... src/names.s"
	@echo "... src/stringb.o"
	@echo "... src/stringb.i"
	@echo "... src/stringb.s"
	@echo "... src/strlxxx.o"
	@echo "... src/strlxxx.i"
	@echo "... src/strlxxx.s"
	@echo "... src/test.o"
	@echo "... src/test.i"
	@echo "... src/test.s"
	@echo "... src/variables.o"
	@echo "... src/variables.i"
	@echo "... src/variables.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

